@istest //test class /calling point
public class VehicleTest {
    
    public static testMethod void main(){
        
           //syntax for create object
             // className obj = new className();
             // syntax for calling methovs 
             // obj.memMethod();
              Vehicle vehicle1 = new Vehicle();
              vehicle1.setValues('V-0001','AP10CM5544','Scorpio',40,'diesel','2014');
              vehicle1.getValues();
        
        
        
    } 
    
}
